(ns build
  (:use lancet))

(def src "src")
(def vendor "vendor")
(def test-dir "test")
(def conjure-src (str vendor "/conjure"))
(def target "target")
(def classes (str target "/classes"))
(def test-app (str target "/test_app"))
(def file-structure "file_structure")
(def default (str file-structure "/default"))

(define-ant-type ant-classpath org.apache.tools.ant.types.Path ant-project)
(define-ant-type pathelement org.apache.tools.ant.types.Path ant-project)

(deftarget compile-conjure "Compile Conjure sources."
  (mkdir { :dir classes })
  (javac { :srcdir src
           :destdir classes
           :debug "on" }))
           
(deftarget jar-conjure "Creates the conjure.jar file."
  (compile-conjure)
  (jar { :jarfile (str target "/conjure.jar")
         :manifest "MANIFEST.MF" }
    (fileset { :dir classes })
    (fileset { :dir file-structure })))

(deftarget clean "Remove autogenerated files and directories."
  (delete { :dir target }))
  
(deftarget test-conjure "Run all of the tests for Conjure."
  (jar-conjure)
  (java { :jar (str target "/conjure.jar")
          :fork "true"
          :dir target
          :args "test_app" })
  (copy { :todir (str test-app "/test") }
    (fileset { :dir test-dir }))
  (echo { :message "\nRunning Tests...\n\n"})
  (java { :classname "clojure.lang.Script"
          :dir test-app
          :fork "true"
          :args "test/run_tests.clj" 
          :classpath 
            (ant-classpath {}
              (pathelement { :path (str test-app "/vendor") })
              (pathelement { :path (str test-app "/app") })
              (pathelement { :path (str test-app "/config") })
              (pathelement { :path (str test-app "/script") })
              (pathelement { :path (str test-app "/db") })
              (pathelement { :path (str test-app "/test") })
              (fileset { :dir (str test-app "/lib")
                         :includes "**/*.jar" })) }))

(deftarget all "Builds all of conjure."
  (jar-conjure)
  (test-conjure))
  
(deftarget default "Executing default target."
  (all))

;(doall (map println (sort (seq (.. ant-project getTaskDefinitions keySet)))))

(if (not-empty *command-line-args*)
  (apply -main *command-line-args*)
  (default))